function HomePage(){
 const T=window.fcTeamsDomain;
 const [teams,setTeams]=window.useStore("teams",window.DEFAULT_SAVED_TEAMS),[profile]=window.useStore("profile",window.DEFAULT_PROFILE),[roster]=window.useStore("roster",window.DEFAULT_ROSTER),[matches,setMatches]=window.useStore("matches",[]),[matchInfo]=window.useStore("matchInfo",null),[,setDraft]=window.useStore("editor",null);
 const [filter,setFilter]=React.useState("all"),[editing,setEditing]=React.useState(null);
 const stats=T.dashboardStats({teams,roster,matches}),scorers=T.topScorers(matches,roster),shown=teams.filter(t=>filter==="all"||t.mode===Number(filter));
 const open=t=>{setDraft(T.createEditorDraft(t,window.FORMATIONS));window.go("editor")};
 const duplicate=t=>setTeams(v=>[...v,T.duplicateTeam(t,{id:`t${Date.now()}`})]);
 const saveMatch=m=>{try{setMatches(v=>T.upsertMatch(v,m,()=>`m${Date.now()}`));setEditing(null)}catch(e){window.__toast?.(e.message)}};
 return <div><GuestModeBanner/><NextMatchBanner matchInfo={matchInfo}/><div className="page-head"><div><div className="page-kicker">{profile.season||"Tu fútbol"}</div><h1 className="page-title">Mis equipos</h1><div className="page-sub">Alineaciones, sorteos y resultados.</div></div><div style={{display:"flex",gap:8}}><button className="btn" onClick={()=>setEditing({})}>+ Resultado</button><button className="btn" onClick={()=>window.go("draw")}>Sortear</button><button className="btn primary" onClick={()=>window.go("mode")}>+ Nuevo equipo</button></div></div>
 <div className="hero-strip"><HomeStat n={String(stats.teams).padStart(2,"0")} l="equipos"/><HomeStat n={stats.players} l="jugadores"/><HomeStat n={String(stats.matches).padStart(2,"0")} l="partidos"/><HomeStat n={stats.lastResult} l={stats.lastMatch?`vs ${stats.lastMatch.opponent}`:"último resultado"}/></div>
 {!!scorers.length&&<section className="scorers-card"><div className="panel-head-row"><span>Goleadores</span></div>{scorers.map((s,i)=><div className="scorer-row" key={s.player.id}><span>{i+1}</span><div className="mini-avatar" style={{background:window.colorFor(s.player.name)}}>{window.initials(s.player.name)}</div><span className="scorer-name">{s.player.name}</span><b>{s.goals}</b></div>)}</section>}
 <div className="section-head"><h2>Equipos guardados</h2><div className="filters">{[["all","Todos"],["5","Fut 5"],["7","Fut 7"],["11","Fut 11"]].map(([id,label])=><button key={id} className={`chip ${filter===id?"lime":""}`} onClick={()=>setFilter(id)}>{label}</button>)}</div></div>
 <div className="teams-grid">{shown.map(t=><article key={t.id} className="team-card"><button className="team-card-main" onClick={()=>open(t)}><Kit design={t.kit||"solid"} primary={t.color||"#e11d48"} secondary={t.secondary||"#0f172a"} number={10} size={76}/><div className="team-card-info"><strong>{t.name}</strong><span>Fut {t.mode} · {t.formation}</span><small>{t.players||0} jugadores</small></div></button><div className="team-card-actions"><button className="btn sm" onClick={()=>open(t)}>Abrir</button><button className="btn sm ghost" onClick={()=>duplicate(t)}>Duplicar</button><button className="btn sm ghost" onClick={()=>confirm(`¿Borrar ${t.name}?`)&&setTeams(v=>v.filter(x=>x.id!==t.id))}>Borrar</button></div></article>)}<button className="team-card new" onClick={()=>window.go("mode")}><div className="new-plus">+</div><div className="new-label">Nuevo equipo</div></button></div>
 <div className="section-head" style={{marginTop:40}}><h2>Accesos rápidos</h2></div><div className="quick-grid"><HomeQuick icon="editorNav" title="Editor" go="editor"/><HomeQuick icon="shuffle" title="Sorteo" go="draw"/><HomeQuick icon="target" title="Modo rival" go="rival"/><HomeQuick icon="jersey" title="Camisetas" go="kits"/></div>
 {editing&&<HomeMatchModal teams={teams} initial={editing.id?editing:null} onClose={()=>setEditing(null)} onSave={saveMatch}/>}</div>
}
function HomeStat({n,l}){return <div className="hero-stat"><div className="hero-stat-n">{n}</div><div className="hero-stat-l">{l}</div></div>}
function HomeQuick({icon,title,go}){return <button className="quick-card" onClick={()=>window.go(go)}><span className="quick-icon"><Icon name={icon} size={20}/></span><strong>{title}</strong></button>}
function GuestModeBanner(){const [session,setSession]=React.useState(undefined);React.useEffect(()=>{window.fcAuth?.session().then(v=>setSession(v||null)).catch(()=>setSession(null))},[]);if(session===undefined||session)return null;return <aside className="guest-banner"><div className="guest-banner-icon">✓</div><div><strong>Modo sin cuenta</strong><span>Tus datos quedan en este dispositivo.</span></div><button className="btn sm ghost" onClick={()=>window.go("settings")}>Backup</button></aside>}
function NextMatchBanner({matchInfo}){if(!matchInfo?.date||matchInfo.date<new Date().toISOString().slice(0,10))return null;return <aside className="next-match-banner"><div><strong>Próximo partido · {matchInfo.date}</strong><span>vs {matchInfo.opponent||"rival"}</span></div><button className="btn sm" onClick={()=>window.go("share")}>Ver</button></aside>}
function HomeMatchModal({teams,initial,onClose,onSave}){const ref=window.useDialogAccessibility(true,onClose),[v,setV]=React.useState({id:initial?.id||null,teamId:initial?.teamId||teams[0]?.id||"",us:initial?.us??0,them:initial?.them??0,opponent:initial?.opponent||"",date:initial?.date||new Date().toISOString().slice(0,10),scorers:initial?.scorers||[]});const p=(k,x)=>setV(c=>({...c,[k]:x}));return <div className="modal-back" onClick={onClose}><div className="modal" ref={ref} role="dialog" aria-modal="true" tabIndex="-1" onClick={e=>e.stopPropagation()}><div className="modal-head"><div className="modal-title">Resultado</div><button className="btn sm ghost" onClick={onClose}>✕</button></div><div className="modal-body"><label className="field"><span>Equipo</span><select value={v.teamId} onChange={e=>p("teamId",e.target.value)}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field"><span>Rival</span><input value={v.opponent} onChange={e=>p("opponent",e.target.value)}/></label><label className="field"><span>Fecha</span><input type="date" value={v.date} onChange={e=>p("date",e.target.value)}/></label><div className="score-editor"><input type="number" min="0" value={v.us} onChange={e=>p("us",e.target.value)}/><span>–</span><input type="number" min="0" value={v.them} onChange={e=>p("them",e.target.value)}/></div></div><div className="modal-foot"><button className="btn ghost" onClick={onClose}>Cancelar</button><button className="btn primary" onClick={()=>onSave(v)}>Guardar</button></div></div></div>}
window.mountPage("page-home",<HomePage/>);
