import Babel from "@babel/standalone";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import { clientEntries } from "./client-entries.mjs";
import { nativeModules } from "./source-files.mjs";
import { nativeEntrySource } from "./native-entry.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const run = promisify(execFile);
const packageJson = JSON.parse(
  await readFile(resolve(root, "package.json"), "utf8"),
);
let commit = process.env.GITHUB_SHA || "local";
try {
  if (commit === "local") {
    commit = (
      await run("git", ["rev-parse", "--short=12", "HEAD"], { cwd: root })
    ).stdout.trim();
  }
} catch {
  /* A downloaded source archive need not contain .git. */
}
await mkdir(resolve(root, "compiled"), { recursive: true });
await writeFile(
  resolve(root, "compiled/release.js"),
  `window.FC_RELEASE=${JSON.stringify({
    version: packageJson.version,
    commit,
    builtAt: new Date().toISOString(),
  })};\n`,
  "utf8",
);

for (const [entry, sourcePath] of Object.entries(clientEntries)) {
  const source = await readFile(resolve(root, sourcePath), "utf8");
  let output;
  if (sourcePath.endsWith(".js")) {
    output = nativeEntrySource(sourcePath, {
      moduleTag: entry === "data",
      targetId: entry,
    });
  } else {
    const result = Babel.transform(source, {
      filename: sourcePath,
      presets: [["react", { runtime: "classic" }]],
      sourceType: "script",
      comments: false,
      compact: false,
    });
    output = `${result.code}\n//# sourceURL=${sourcePath}\n`;
  }
  await writeFile(resolve(root, "compiled", `${entry}.js`), output, "utf8");
}
const modules = (await nativeModules(root)).map((path) => `./${path}`);
await writeFile(
  resolve(root, "compiled/module-precache.js"),
  `// Generated by scripts/build-client.mjs.\nself.FC_MODULE_PRECACHE = ${JSON.stringify(modules, null, 2)};\n`,
  "utf8",
);
console.log(
  `Compiladas ${Object.keys(clientEntries).length} entradas y ${modules.length} módulos offline.`,
);
